name: Smelly Python Fix
description: Fix for the smelly python action
inputs:
  dir:
    description: "Directory to run smelly-python in (Default: Src)"
    default: 'src'
  token:
    description: GitHub token
    required: true
runs:
  using: composite
  steps:
    - name: Get Space
      uses: easimon/maximize-build-space@master
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install Pipenv
      shell: bash
      run: pip install pipenv
    - name: Get New Version
      shell: bash
      run: |
        git clone https://github.com/NathanCFoster/smelly-python.git
        cd smelly-python
        git checkout fix/16
        pipenv lock
        pipenv requirements > requirements.txt
        pip install -r requirements.txt
        pip install .
        cd ..
    - name: Generate Report from smelly-python
      shell: bash
      run: pipenv run smelly-python -d src
    - name: Save output folder with html report
      uses: actions/upload-artifact@v4
      with:
        name: smelly-python-html-report
        path: |
          ${{ github.workspace }}/report/smelly_python/**/*
          ${{ github.workspace }}/report/smelly_python/**/full_data.md
          !${{ github.workspace }}/report/smelly_python/**/*.md
    - name: Set job summary
      shell: bash
      run: cat ${{ github.workspace }}/report/smelly_python/comment.md >> $GITHUB_STEP_SUMMARY
    - name: Get PR number
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: echo "pr_number=`gh pr view ${{ github.event.number }} --json number -q '.number'`" >> $GITHUB_ENV
    - name: Delete old comments
      if: ${{ env.pr_number != '' }}
      uses: maheshrayas/action-pr-comment-delete@v1
      with:
        github_token: ${{ inputs.token }}
        org: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        user: github-actions[bot]
        issue: ${{ env.pr_number }}
    - name: Post Comment
      if: ${{ env.pr_number != '' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: gh pr comment ${{ github.event.number }} -F ${{ github.workspace }}/report/smelly_python/comment.md
