name: "Update Sam Template"
description: "Composite action for deploying/updating a sam application"
inputs:
  location:
    description: "Directory of the sam template"
    required: "true"
  sam_package_config:
    description: "All params for packaging the template, only for use with sam_config"
  sam_config:
    description: "All required params for deploying template, by default it will look for samconfig.toml"
    default: "true"
  region:
    description: "AWS Region to deploy to (Defult: us-east-1)"
    default: "us-east-1"
  role_to_assume:
    description: "Role to assume when deploying the sam template"
    required: true
  python_v:
    description: "Python version of the sam template"
    default: "3.8"

runs:
  using: composite
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_v }}
    - name: Setup sam
      uses: aws-actions/setup-sam@v2
    - name: Deploy PermissionSetResources Stackset
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role_to_assume }}
    - name: Deploy sam
      shell: bash
      working-directory: ${{ inputs.location }}
      run: |
        if [[ ${{ inputs.sam_config }} == "true" ]]
        then
        sam build --use-container
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        else
        sam package ${{ inputs.sam_package_config }}
        sam deploy ${{ inputs.sam_config }} --no-confirm-changeset --no-fail-on-empty-changeset
        fi
