name: "Lambda ECR Deploy"
description: "Deployment action for ECR primarily used for lambdas"

inputs:
  role_to_assume:
    description: "The arn of the role to assume"
    required: true
  repository:
    description: "The ECR repo to deploy to"
    required: true
  region:
    description: "The region of the ecr repo (Default: us-east-1)"
    default: us-east-1
  location:
    description: "Location of a directory containing the Dockerfile"
    required: true

runs:
  using: composite
  steps:
    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role_to_assume }}
        aws-region: ${{ inputs.region }}
    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr
    - name: Build, tag, and push image to ECR
      shell: bash
      working-directory: ${{ inputs.location }}
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REPOSITORY .
        docker tag $REPOSITORY:latest $REGISTRY/$REPOSITORY:latest
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
